"""initial schema

Revision ID: 8419f67a98c6
Revises: 
Create Date: 2026-04-21 12:34:21.997621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8419f67a98c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    schema='chatbot'
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'supervisor', 'agent', name='user_role', native_enum=False, length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='chatbot'
    )
    op.create_table('bot',
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.Enum('web', 'whatsapp', 'drip', name='bot_channel', native_enum=False, length=16), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['chatbot.site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_index(op.f('ix_chatbot_bot_public_key'), 'bot', ['public_key'], unique=True, schema='chatbot')
    op.create_table('conversation',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('bot', 'queued', 'assigned', 'closed', name='conversation_status', native_enum=False, length=16), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['chatbot.bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_index(op.f('ix_chatbot_conversation_visitor_id'), 'conversation', ['visitor_id'], unique=False, schema='chatbot')
    op.create_table('flow',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['chatbot.bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_table('assignment',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('manual', 'round_robin', name='assignment_mode', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['chatbot.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot.conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['chatbot.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_index(op.f('ix_chatbot_assignment_conversation_id'), 'assignment', ['conversation_id'], unique=False, schema='chatbot')
    op.create_table('flow_version',
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['chatbot.flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'version', name='uq_flow_version'),
    schema='chatbot'
    )
    op.create_table('lead',
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['chatbot.bot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot.conversation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_index(op.f('ix_chatbot_lead_email'), 'lead', ['email'], unique=False, schema='chatbot')
    op.create_index(op.f('ix_chatbot_lead_phone'), 'lead', ['phone'], unique=False, schema='chatbot')
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('visitor', 'bot', 'agent', 'system', name='message_sender', native_enum=False, length=16), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot.conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['chatbot.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='chatbot'
    )
    op.create_index(op.f('ix_chatbot_message_conversation_id'), 'message', ['conversation_id'], unique=False, schema='chatbot')
    op.create_table('lead_utm',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('utm_source', sa.String(length=120), nullable=True),
    sa.Column('utm_medium', sa.String(length=120), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('utm_term', sa.String(length=120), nullable=True),
    sa.Column('utm_content', sa.String(length=120), nullable=True),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('fbclid', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('landing_url', sa.String(length=1024), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['chatbot.lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id'),
    schema='chatbot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_utm', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_message_conversation_id'), table_name='message', schema='chatbot')
    op.drop_table('message', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_lead_phone'), table_name='lead', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_lead_email'), table_name='lead', schema='chatbot')
    op.drop_table('lead', schema='chatbot')
    op.drop_table('flow_version', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_assignment_conversation_id'), table_name='assignment', schema='chatbot')
    op.drop_table('assignment', schema='chatbot')
    op.drop_table('flow', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_conversation_visitor_id'), table_name='conversation', schema='chatbot')
    op.drop_table('conversation', schema='chatbot')
    op.drop_index(op.f('ix_chatbot_bot_public_key'), table_name='bot', schema='chatbot')
    op.drop_table('bot', schema='chatbot')
    op.drop_table('user', schema='chatbot')
    op.drop_table('site', schema='chatbot')
    # ### end Alembic commands ###
